### PR TITLE
update require to julia 0.3

### PR DESCRIPTION
**Pull request by tkelman**
assuming no one is continuing to test with anything earlier

### CODE REVIEW

**Comment by stevengj** [comment]
LGTM.

**Comment by carlobaldassi** [comment]
Sorry, I don't get the reason for this. Wasn't it working with julia 0.2 still?
(I'm still testing with julia 0.2 in some cases.)

**Comment by tkelman** [comment]
Oh if you're still testing, then we can change it back to 0.2. Shouldn't be putting prereleases there though, so leave off the dash.

**Comment by tkelman** [comment]
So far from the evidence I've seen, you're the only person who has said you're still testing any packages against 0.2 @carlobaldassi - just so I'm aware for future reference, is there some subset you have written down anywhere of which packages you're continuing to do this on? I don't want to step on any toes but I don't think we'll be set up to easily test Linux binaries of anything prior to 0.3 in an automated way going forward.

**Comment by carlobaldassi** [comment]
Yes, it seems like I'm the only one still testing on 0.2. For the record, I'm not at all against removing support going forward, I was just surprised in this case since no breaking functionality was introduced to explain the change.
Anyway, the packages (besides Options) which I'm either maintaining of involved with somehow and which still support 0.2 are: [ArgParse](https://github.com/carlobaldassi/ArgParse.jl), [FastaIO](https://github.com/carlobaldassi/FastaIO.jl), [TextWrap](https://github.com/carlobaldassi/TextWrap.jl), [GLPK](https://github.com/JuliaOpt/GLPK.jl/blob/master/REQUIRE), [Gaston](https://github.com/mbaz/Gaston.jl).

**Comment by tkelman** [comment]
Cool, thanks. I tend to operate under the assumption that if something isn't actively tested, it probably doesn't work. Really the only reason to worry about being particular on the lower bound in `REQUIRE` is in case users get ahold of an old version of julia from somewhere (outdated distro package manager maybe), try to install packages and none of them work. If we make it easy to test on different versions (https://github.com/travis-ci/travis-build/pull/487), then package authors can easily find out the most recent version of their package that works for any given version of Julia, and adjust `REQUIRE` on tags in metadata accordingly.

All of those packages should probably drop the `-` on the Julia version number, since that means prereleases of that version, not "and up."

**Pull request merged**
